export default {
  login: 'Login',
  register: 'Register',
  userNamePlaceHolder: 'User Name ....',
  emailPlaceholder: 'Email....',
  passwordPlaceholder: 'Password....',
  facebook: 'Facebook',
  google: 'Google',
  forgetPwd: 'forget Password?',
  language: 'Language',
  price: 'Price',
  buy: 'Buy Now',
  logout: 'Logout',
  logoutAlert: 'Logout successful',
  addCart: 'Add to Cart',
  addCartAlert: 'Successful added',
  loginSuccess: 'Login successful',
  error: 'Something wrong?',
  productDetail: 'Detail',
};
